services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: api_app
      POSTGRES_USER: api_app
      POSTGRES_PASSWORD: api_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: api_app
      POSTGRES_USER: api_app
      POSTGRES_PASSWORD: api_app
      POSTGRES_HOST: db
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "api_application.settings"
    depends_on:
      - db
    command: >
      sh -c "sleep 2 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: